swagger: "2.0"
info:
  description: "This is a Image Resize server."
  version: "1.0.0"
  title: "Image Resize"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "fedorenko.tolik@gmail.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "imageresize.swagger.io"
basePath: "/v2"
tags:
- name: "image"
  description: "Resize your images"
  externalDocs:
    description: "Find out more"
    url: "http://swagger.io"
schemes:
- "http"
paths:
  /images:
    post:
      tags:
      - "image"
      summary: "uploads an image"
      description: ""
      operationId: "uploadFile"
      consumes:
      - "multipart/form-data"
      produces:
      - "application/json"
      parameters:
      - name: "additionalMetadata"
        in: "formData"
        description: "Additional data to pass to server"
        required: false
        type: "string"
      - name: "file"
        in: "formData"
        description: "file to upload"
        required: false
        type: "file"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/ApiResponse"
      
  /images/{imageId}:
    get:
      tags:
      - "image"
      summary: "Shows the image"
      description: ""
      operationId: "imageShow"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - name: "imageId"
        in: "path"
        description: "Image Id to show image"
        required: true
        type: "integer"
      responses:
        200:
          description: "success"
          schema:
            $ref: "#/definitions/Image"
        400:
          description: "Invalid Image Id"

definitions:
  Image:
    type: "object"
    required:
    - "imageURL"
    properties:
      id:
        type: "integer"
        format: "int64"
      imageURL:
        type: "string"
        example: "PathToTheFile"
    xml:
      name: "image"
  ApiResponse:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      type:
        type: "string"
      message:
        type: "string"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"