// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi Image Resize
This is a Image Resize server.

Terms Of Service:

http://swagger.io/terms/


    Schemes:
      http
    Host: imageresize.swagger.io
    BasePath: /v2
    Version: 1.0.0
    License: Apache 2.0 http://www.apache.org/licenses/LICENSE-2.0.html
    Contact: <fedorenko.tolik@gmail.com>

    Consumes:
    - multipart/form-data

    Produces:
    - application/json
    - application/xml

swagger:meta
*/
package restapi
