// Code generated by go-swagger; DO NOT EDIT.

package image

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewImageShowParams creates a new ImageShowParams object
// no default values defined in spec.
func NewImageShowParams() ImageShowParams {

	return ImageShowParams{}
}

// ImageShowParams contains all the bound params for the image show operation
// typically these are obtained from a http.Request
//
// swagger:parameters imageShow
type ImageShowParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Image Id to show image
	  Required: true
	  In: path
	*/
	ImageID int64
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewImageShowParams() beforehand.
func (o *ImageShowParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rImageID, rhkImageID, _ := route.Params.GetOK("imageId")
	if err := o.bindImageID(rImageID, rhkImageID, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *ImageShowParams) bindImageID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	value, err := swag.ConvertInt64(raw)
	if err != nil {
		return errors.InvalidType("imageId", "path", "int64", raw)
	}
	o.ImageID = value

	return nil
}
