// Code generated by go-swagger; DO NOT EDIT.

package image

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "ImageResizeWithSwagger/models"
)

// ImageShowOKCode is the HTTP code returned for type ImageShowOK
const ImageShowOKCode int = 200

/*ImageShowOK success

swagger:response imageShowOK
*/
type ImageShowOK struct {

	/*
	  In: Body
	*/
	Payload *models.Image `json:"body,omitempty"`
}

// NewImageShowOK creates ImageShowOK with default headers values
func NewImageShowOK() *ImageShowOK {

	return &ImageShowOK{}
}

// WithPayload adds the payload to the image show o k response
func (o *ImageShowOK) WithPayload(payload *models.Image) *ImageShowOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the image show o k response
func (o *ImageShowOK) SetPayload(payload *models.Image) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ImageShowOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ImageShowBadRequestCode is the HTTP code returned for type ImageShowBadRequest
const ImageShowBadRequestCode int = 400

/*ImageShowBadRequest Invalid Image Id

swagger:response imageShowBadRequest
*/
type ImageShowBadRequest struct {
}

// NewImageShowBadRequest creates ImageShowBadRequest with default headers values
func NewImageShowBadRequest() *ImageShowBadRequest {

	return &ImageShowBadRequest{}
}

// WriteResponse to the client
func (o *ImageShowBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}
